export const ACTypes = {
  SET_AUTH_USER: "SET_AUTH_USER",
  SET_AUTH_BUSINESS: "SET_AUTH_BUSINESS",
  SIGNOUT: "SIGNOUT",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  SET_USER_LOCATION: "SET_USER_LOCATION",

  SET_ALL_BOXES: "GET_ALL_BOXES",
  SET_ALL_CUISINE: "GET_ALL_CUISINE",
};