export const ACTypes = {
  SET_AUTH_USER: "SET_AUTH_USER",
  SET_AUTH_BUSINESS: "SET_AUTH_BUSINESS",
  SIGNOUT: "SIGNOUT",
  SET_ACTIVE_BOXES: "SET_ACTIVE_BOXES",
  ADD_NEW_BOX: "ADD_NEW_BOX",
  EDIT_BOX: "EDIT_BOX",
  DELETE_BOX: "DELETE_BOX"
};
